CREATE TABLE IF NOT EXISTS languages (
  lang TEXT PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS codes (
  id TEXT PRIMARY KEY,
  lang TEXT NOT NULL,
  code TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS embeddings (
  code_id TEXT PRIMARY KEY REFERENCES codes(id),
  dim INTEGER NOT NULL,
  vector FLOAT[] NOT NULL
);
